basic_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from basic_app import views

# TEMPLATE TAGGING
app_name = "basic_app"

urlpatterns = [
    url(r'^registration', views.register, name='register'),
    url(r'^$', views.index, name='index'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special'),
    url(r'^login/', views.user_login, name='login'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name='index'),
    url(r'^basic_app/', include('basic_app.urls')),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pic", blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
# Create your views here.


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You're logged in")


def index(request):
    return render(request, 'basic_app/index.html')


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basic_app/registration.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
    })


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            return HttpResponse("LOGIN FAILED")
    else:
        return render(request, 'basic_app/login.html')

basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a href={% url 'index' %} class="navbar-brand">DJANGO</a></li>
        <li><a href={% url 'admin:index' %} class="navbar-link">Admin</a></li>
        <li><a href={% url 'basic_app:register' %} class="navbar-link">Register</a></li>
        {% if user.is_authenticated %}
          <li><a href={% url 'basic_app:logout' %} class="navbar-link">Logout</a></li>
        {% else %}
          <li><a href={% url 'basic_app:login' %} class="navbar-link">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block body_block %}
      
    {% endblock body_block %}
  </div>
</body>
</html>

basic_app/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Django Level 5</h1>
  </div>
{% endblock body_block %}

basic_app/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please login</h1>
    <form action={% url 'basic_app:login' %} method="POST">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password</label>
      <input type="password" name="password">
      <input type="submit" name="submit" value="Login">
    </form>
  </div>
{% endblock body_block %}

basic_app/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering!</h1>
    {% else %}
      <h1>Fill out the form:</h1>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="submit">
      </form>
    {% endif %} 
  </div>

{% endblock body_block %}